# MS: CHANGED SYSPORT		=	-DLINUX -DGENERIC_SYSV
# This is how my Linux works.

SYSPORT		=	-DLINUX -DPOSIX -pipe 

CPP             =       g++
CC		=	gcc
LD		=	gcc
MKDPND		=	g++ -MM $(CFL)
LEX		=	flex
YACC		=	bison -y
DIFF		=	diff

ZONEDIR		=	zon/
