SYSPORT		=	-DSOLARIS -DGENERIC_SYSV

CC		=	gcc
LD		=	gcc
MKDPND		=	gcc -MM $(CFL)
LEX		=	flex
YACC		=	bison -y
DIFF		=	diff

ZONEDIR		=	zon/
EXTRA_LDLIBS	=	-lsocket -lnsl
MPLEX_LDLIBS	=	-lsocket -lnsl
